name: Deploy to AWS Elastic Beanstalk


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    name: Build Spring Boot Application
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2


      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"


      # Build the project using Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests


      # List files in target directory (to verify the JAR is generated)
      - name: List files in target directory
        run: ls -la target


      # Upload the built JAR as an artifact for the deploy step
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: jar-file
          path: target/*.jar


  deploy:
    name: Deploy to AWS Elastic Beanstalk
